### ISSUE TITLE
gucumber.T.Fail undefined (type gucumber.Tester has no field or method Fail)

### ISSUE THREAD

**Issue by amorellp** [gucumber/gucumber#17]
Hi there! I am getting the error message in the title. In the documentation is written "The T value is a testing.T style value that represents the test context for each test. It mostly supports Errorf(fmt, args...), but also supports other convenience methods." but in the code looks like this is not true (and the compiler have the same opinion ;):
- file step_def.go:
var (
	GlobalContext = [...]

	T Tester
        [...]
)

type Context struct {
       [...]
       T               Tester
}

- file runner.go:
type Tester interface {
	Errorf(format string, args ...interface{})
	Skip(args ...interface{})
}

Am I wrong?
Greetings, 

Alberto

**Comment by lsegal** [comment]
Fail is not (yet) supported, but if you opened a PR to add it, I'd take a look. Seems to be working as intended.
