### ISSUE TITLE
Unable to run sample in readme.md

### ISSUE THREAD

**Issue by danvallejo** [gucumber/gucumber#35]
> gucumber internal/features/accounts  --or-- gucumber
Windows

package main:
internal\features\accounts\_test\gucumbertest__.go:6:10: unknown escape sequence

I see this file created:
_test\gucumbertest__.go
package main

import (
	"github.com/gucumber/gucumber"
	_i0 "..\internal\features\accounts"
	
)

var (
	_ci0 = _i0.IMPORT_MARKER
	
)

func main() {
	
	gucumber.GlobalContext.RunDir("internal/features")
}

**Comment by lsegal** [comment]
This looks like a bug related to the generation of the main test file's import path format. I'm not entirely sure why this hasn't been reported. Do you have more reproduction steps?

**Comment by danvallejo** [comment]
Create D:\src\test
GOROOT=C:\Go\
Set GOPATH=D:\src\test
Create internal\features\accounts folder
Place login.feature and step_definitions.go from your readme.md
From D:\src\test run gucumber
D:\src\test> gucumber
package main:
internal\features\_test\gucumbertest__.go:6:10: unknown escape sequence

Do you have a -debug flag that I can pass to give more output? Or a log file?

**Comment by danvallejo** [comment]
If I unset GOPATH
panic: could not determine package path for internal\features\accounts\step_definitions.go

goroutine 1 [running]:
github.com/gucumber/gucumber.RunMain()
        C:/Users/dan/go/src/github.com/gucumber/gucumber/run_main.go:42 +0x234
main.main()
        C:/Users/dan/go/src/github.com/gucumber/gucumber/cmd/gucumber/gucumber.go:6 +0x27

**Comment by danvallejo** [comment]
go get installs to C:\Users\dan\go\src

**Comment by lsegal** [comment]
@danvallejo just tested this and it should work correctly now.

**Comment by danvallejo** [comment]
Am I in the right directory to run gucumber? The internal directory is under Contact.

```
D:\..\Contact> gucumber                                                                                          
internal\features\_test\gucumbertest__.go:6:2: cannot find package "../internal/features/accounts" in:                                                                                                  
        D:\..\Contact\internal\features\internal\features\accounts                                                                                   
internal\features\_test\gucumbertest__.go:5:2: cannot find package "github.com/gucumber/gucumber" in any of:                                                                                            
        C:\Go\src\github.com\gucumber\gucumber (from $GOROOT)                                       
        D:\..\Contact\src\github.com\gucumber\guc
umber (from $GOPATH)                                                                                

package main

import (
	"github.com/gucumber/gucumber"
	_i0 "../internal/features/accounts"
	
)

var (
	_ci0 = _i0.IMPORT_MARKER
	
)

func main() {
	
	gucumber.GlobalContext.RunDir("internal/features")
}
```

**Comment by danvallejo** [comment]
Shouldn't it be ./internal/features instead of ../internal/features ?

I unset GOPATH.

> gucumber
panic: could not determine package path for internal\features\accounts\step_definitions.go

goroutine 1 [running]:
github.com/gucumber/gucumber.RunMain()
        C:/Users/dan/go/src/github.com/gucumber/gucumber/run_main.go:42 +0x234
main.main()
        C:/Users/dan/go/src/github.com/gucumber/gucumber/cmd/gucumber/gucumber.go:6 +0x27

**Comment by lsegal** [comment]
You should set a GOPATH to the root of your Go workspace. What was your GOPATH set to initially?

**Comment by danvallejo** [comment]
GOPATH was initially not set. Then I set it to the directory of the code
that I was working with to try to get further.

By default if GOPATH is not set it goes to the users folder
(c:\users\dan\go)

**Comment by lsegal** [comment]
The GOPATH should not be set to your current directory, it should be set to your Go workspace. Packages should be inside of `$GOPATH/src/*`. I would recommend reading about how Go uses the GOPATH to resolve packages here: https://golang.org/doc/code.html#GOPATH -- pay close attention to the path structure they use for the next "Your First Program" section, specifically the subdirectories being used.
